import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import {
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  mkdirSync,
  writeFileSync,
  existsSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

for (const presentation of ['staging', 'production']) {
  test(`${presentation} generated bytes identify the six-tool product and indexing policy`, () => {
    const out = mkdtempSync(join(tmpdir(), 'oe-presentation-'));
    try {
      mkdirSync(join(out, 'assets'));
      writeFileSync(join(out, 'assets', 'stale-presentation.js'), 'stale presentation');
      const env = { ...process.env, OE_RELEASE_BUILD: '0' };
      // The staging case verifies the fail-safe default, not just an explicit value.
      if (presentation === 'staging') delete env.OE_PRESENTATION;
      else env.OE_PRESENTATION = presentation;
      execFileSync(process.execPath, ['node_modules/vite/bin/vite.js', 'build', '--outDir', out], {
        env,
        stdio: 'pipe',
      });
      assert.equal(existsSync(join(out, 'assets', 'stale-presentation.js')), false);
      const html = readFileSync(join(out, 'index.html'), 'utf8');
      const robots = readFileSync(join(out, 'robots.txt'), 'utf8');
      const metadata = JSON.parse(readFileSync(join(out, 'build.json'), 'utf8'));
      const js = readdirSync(join(out, 'assets'))
        .filter((f) => f.endsWith('.js'))
        .map((f) => readFileSync(join(out, 'assets', f), 'utf8'))
        .join('\n');
      assert.equal(metadata.presentation, presentation);
      assert.equal(metadata.version, JSON.parse(readFileSync('package.json', 'utf8')).version);
      const staging = presentation === 'staging';
      assert.ok(
        html.includes(`name="robots" content="${staging ? 'noindex, nofollow' : 'index, follow'}"`),
      );
      assert.equal(robots, staging ? 'User-agent: *\nDisallow: /\n' : 'User-agent: *\nAllow: /\n');
      const noscript = html.match(/<noscript>([\s\S]*?)<\/noscript>/)[1];
      for (const name of [
        'Decision Room',
        'Next Move',
        'Build a Standard',
        'Reset',
        'Rebuild Map',
        'Do It Now',
      ]) {
        assert.ok(noscript.includes(name));
        assert.ok(js.includes(name));
      }
      assert.match(noscript, /available with JavaScript enabled/);
      assert.equal(noscript.includes('Not a production release'), staging);
      assert.equal(js.includes('Development staging'), staging);
      assert.equal(js.includes('Not a production release'), staging);
      assert.equal(js.includes('14 rotated logs'), staging);
      assert.doesNotMatch(
        html + js,
        /available on staging|other tools are in development|Interaction preview|Sample action card|Tool outline|This tool is not available yet|#\/preview/,
      );
      for (const policy of [
        "connect-src 'none'",
        "form-action 'none'",
        "script-src 'self'",
        "object-src 'none'",
        "base-uri 'none'",
      ])
        assert.ok(html.includes(policy));
      assert.doesNotMatch(html, /<script[^>]+src="https?:/);
    } finally {
      rmSync(out, { recursive: true, force: true });
    }
  });
}
test('unknown presentation mode fails instead of producing indexable output', () => {
  const result = spawnSync(process.execPath, ['node_modules/vite/bin/vite.js', 'build'], {
    env: { ...process.env, OE_PRESENTATION: 'prod', OE_RELEASE_BUILD: '0' },
    encoding: 'utf8',
  });
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /OE_PRESENTATION must be staging or production/);
});
